name: "사이트 삭제"
description: "만물상자에서 사이트를 삭제합니다."
labels: ["delete"]
body:
  - type: markdown
    attributes:
      value: "아래 사이트가 삭제됩니다. 확인 후 제출하세요."
  - type: input
    id: name
    attributes:
      label: "이름"
    validations:
      required: true
  - type: input
    id: category
    attributes:
      label: "카테고리"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: "URL"
    validations:
      required: false
