name: "사이트 삭제"
description: "만물상자에서 사이트를 삭제합니다."
labels: ["delete"]
body:
  - type: dropdown
    id: target
    attributes:
      label: "삭제할 사이트"
      description: "\"카테고리 | 사이트 이름\" 형식입니다. 현재 정보는 이슈 생성 후 코멘트로 표시됩니다."
      options:
        - "글쓰기 | 사람인 맞춤법 검사기"
        - "글쓰기 | 웨않되"
        - "글쓰기 | Grammarly"
        - "글쓰기 | DeepL 번역기"
        - "글쓰기 | WordReference 사전"
        - "글쓰기 | 클로바 더빙"
        - "글쓰기 | Scholarcy"
        - "글쓰기 | turnitin"
        - "글쓰기 | 아보카도"
        - "글쓰기 | copy.ai"
        - "글쓰기 | jasper"
        - "글쓰기 | Speechify"
        - "글쓰기 | Templify"
        - "글쓰기 | Academic Phrasebank"
        - "글쓰기 | Trinka"
        - "글쓰기 | Lorem Ipsum 생성기"
        - "연구 | Semantic Scholar"
        - "연구 | Google  Scholar"
        - "연구 | Scholar Inbox"
        - "연구 | Hugging Face - Daily Papers"
        - "연구 | ResearchTrend.AI"
        - "연구 | alphaXiv"
        - "연구 | Scispace"
        - "연구 | Connected Papers"
        - "연구 | Elicit"
        - "연구 | OpenRead"
        - "변환 | 이미지 병합하기"
        - "변환 | ezgif"
        - "변환 | Mathpix"
        - "변환 | VEED.IO"
        - "변환 | 유튜브 썸네일 추출하기"
        - "변환 | 자모야 모여라"
        - "변환 | 지수 표기법 변환기"
        - "변환 | Time Zone Converter"
        - "변환 | Photopea"
        - "변환 | remove.bg"
        - "변환 | Image Backgorund blurer"
        - "변환 | ClipDrop"
        - "변환 | Color conversion"
        - "개발 | carbon"
        - "개발 | Algorithm Visualizer"
        - "개발 | Visualgo"
        - "개발 | Momen"
        - "개발 | Durable"
        - "개발 | CSS Peeper"
        - "개발 | shortcuts design"
        - "개발 | Type Scale"
        - "개발 | Wikipedia TeX formula"
        - "개발 | Overleaf"
        - "개발 | Latex Editor"
        - "개발 | Overleaf 'List of Greek letters and math symbols'"
        - "시각화 | Diagrams"
        - "시각화 | Desmos"
        - "시각화 | DataGraph"
        - "시각화 | Online 3D Viewer"
        - "시각화 | Apption"
        - "시각화 | 워드클라우드"
        - "시각화 | Epic Pen"
        - "시각화 | Napkin AI"
        - "디자인소재 | Coolors"
        - "디자인소재 | Color Hunt"
        - "디자인소재 | 크로마"
        - "디자인소재 | 투 컬러 콤비네이션"
        - "디자인소재 | uiGradients"
        - "디자인소재 | WebGradients"
        - "디자인소재 | lol colors"
        - "디자인소재 | Flat UI colors"
        - "디자인소재 | 컬러헥사"
        - "디자인소재 | 디자인 씨드"
        - "디자인소재 | Grabient"
        - "디자인소재 | 엔사이컬러피디아"
        - "디자인소재 | 브랜드 컬러스"
        - "디자인소재 | Color by Fardos - Color Picker"
        - "디자인소재 | ColorZilla"
        - "디자인소재 | Picular"
        - "디자인소재 | Snook Color Contrast"
        - "디자인소재 | Candy Icons"
        - "디자인소재 | ColorSpace"
        - "디자인소재 | AI Colors"
        - "디자인소재 | AutoDraw"
        - "디자인소재 | Noun Project"
        - "디자인소재 | Font Awesome"
        - "디자인소재 | 구글 폰트 아이콘"
        - "디자인소재 | Flaticon"
        - "디자인소재 | Emoji Engine"
        - "디자인소재 | emojipedia"
        - "디자인소재 | manypixels - icon"
        - "디자인소재 | Animated Emoji"
        - "디자인소재 | SVG Repo"
        - "디자인소재 | 아이콘 몬스터"
        - "디자인소재 | 아이콘 스토어"
        - "디자인소재 | Human Pictogram 2.0"
        - "디자인소재 | lordicon"
        - "디자인소재 | icons8"
        - "디자인소재 | IconScout"
        - "디자인소재 | 특수문자 표"
        - "디자인소재 | 토스페이스"
        - "디자인소재 | 3icons"
        - "디자인소재 | Free3Dicon"
        - "디자인소재 | Love 3D Icon"
        - "디자인소재 | Noticon"
        - "디자인소재 | Notion Icons"
        - "디자인소재 | Feather"
        - "디자인소재 | Unsplash"
        - "디자인소재 | Pixabay"
        - "디자인소재 | Pexels"
        - "디자인소재 | unDraw"
        - "디자인소재 | Shopify"
        - "디자인소재 | Picjumbo"
        - "디자인소재 | BGJar"
        - "디자인소재 | IRA design"
        - "디자인소재 | 소코스트"
        - "디자인소재 | Loose Drawing"
        - "디자인소재 | 비즈니스소재"
        - "디자인소재 | doodle svg"
        - "디자인소재 | 국토지리정보원 어린이지도여행"
        - "디자인소재 | storyset"
        - "디자인소재 | manypixels - 일러스트"
        - "디자인소재 | MagicPattern"
        - "디자인소재 | Ira Design"
        - "디자인소재 | Pixels Market"
        - "디자인소재 | 휴먼즈"
        - "디자인소재 | videvo"
        - "디자인소재 | 공유마당"
        - "디자인소재 | Mock Magic"
        - "디자인소재 | placeit"
        - "디자인소재 | IconFinder"
        - "디자인소재 | coverr"
        - "디자인소재 | VIDEVO"
        - "디자인소재 | Vecteezy"
        - "디자인소재 | SkalGubbar"
        - "디자인소재 | Cut out people"
        - "디자인소재 | MrCutOut"
        - "디자인소재 | Shapefest"
        - "디자인소재 | Lace"
        - "디자인소재 | 후키다시 디자인"
        - "디자인소재 | 프리 라인 디자인"
        - "디자인소재 | 브이월드"
        - "디자인소재 | 스마트 서울맵 3D 서울지도"
        - "디자인소재 | OpenDoodles"
        - "디자인소재 | EVERYPIXEL"
        - "디자인소재 | DrawKit"
        - "디자인소재 | 눈누"
        - "디자인소재 | DaFont"
        - "디자인소재 | Google Fonts"
        - "디자인소재 | 1001 Fonts"
        - "템플릿 | beautiful.ai"
        - "템플릿 | TOME.app"
        - "템플릿 | Gamma"
        - "템플릿 | Notion Svg Avatar Maker"
        - "템플릿 | Notion Cover Generator"
        - "템플릿 | Covercons"
        - "템플릿 | 미리캔버스"
        - "템플릿 | Awwwards.com"
        - "템플릿 | PosterPresetations"
        - "템플릿 | Notion Everything"
        - "템플릿 | Template Haven"
        - "템플릿 | Notion Pages"
        - "템플릿 | Notion Box"
        - "템플릿 | 템플래닛"
        - "템플릿 | aNotioneer"
        - "템플릿 | 농립식품기술기획평가원 자료실"
        - "템플릿 | 정부 R&D 부처합동설명회"
        - "템플릿 | 한국과학기술기획평가원 부처합동 설명회"
        - "템플릿 | notefolio"
        - "통계·동향 | 빅카인즈"
        - "통계·동향 | 갤럽"
        - "통계·동향 | 구글트렌드"
        - "통계·동향 | 대한민국 정책브리핑"
        - "통계·동향 | KOTRA 해외 시장 뉴스"
        - "통계·동향 | IEEE Spectrum"
        - "브랜딩 | 네임릭스"
        - "브랜딩 | Logo Maker"
        - "브랜딩 | mybrandnewlogo"
        - "브랜딩 | Shopify logo maker"
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: "삭제 사유 (선택)"
      placeholder: "삭제 이유를 적어주세요"
    validations:
      required: false
